### ISSUE TITLE
Weird production setting for /nova-settings

### ISSUE THREAD

**Issue by flatcapco** [outl1ne/nova-settings#178]
I'm having an issue with the latest version of Nova, when I try to view the nova-settings page which is registered correctly (and works locally) I receive the error below. both installations are running php 8.1, thanks for any help to debug! The route:list shows the correct url and the nova settings table is working as expected.. even if I insert a key value into it I can access it just fine.. so its just the settings page which is the default route? I havent added any permissions to view (accessible to all)

Thanks!

```

[2023-12-18 10:06:55] production.ERROR: Target class [O:47:"Laravel\SerializableClosure\SerializableClosure":1:{s:12:"serializable";O:46:"Laravel\SerializableClosure\Serializers\Signed":2:{s:12:"serializable";s:356:"O:46:"Laravel\SerializableClosure\Serializers\Native":5:{s:3:"use";a:1:{s:4:"path";s:13:"nova-settings";}s:8:"function";s:95:"fn ($pageId = 'general') => inertia('NovaSettings', ['basePath' => $path, 'pageId' => $pageId])";s:5:"scope";s:48:"Outl1ne\NovaSettings\NovaSettingsServiceProvider";s:4:"this";N;s:4:"self";s:32:"00000000000008330000000000000000";}";s:4:"hash";s:44:"f339LyrqsU40URDGjug6LvWDqCA29w5A/v5HpjWEpW8=";}}] does not exist. {"userId":1,"exception":"[object] (Illuminate\\Contracts\\Container\\BindingResolutionException(code: 0): Target class [O:47:\"Laravel\\SerializableClosure\\SerializableClosure\":1:{s:12:\"serializable\";O:46:\"Laravel\\SerializableClosure\\Serializers\\Signed\":2:{s:12:\"serializable\";s:356:\"O:46:\"Laravel\\SerializableClosure\\Serializers\\Native\":5:{s:3:\"use\";a:1:{s:4:\"path\";s:13:\"nova-settings\";}s:8:\"function\";s:95:\"fn ($pageId = 'general') => inertia('NovaSettings', ['basePath' => $path, 'pageId' => $pageId])\";s:5:\"scope\";s:48:\"Outl1ne\\NovaSettings\\NovaSettingsServiceProvider\";s:4:\"this\";N;s:4:\"self\";s:32:\"00000000000008330000000000000000\";}\";s:4:\"hash\";s:44:\"f339LyrqsU40URDGjug6LvWDqCA29w5A/v5HpjWEpW8=\";}}] does not exist. at /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Container/Container.php:891)
[stacktrace]
#0 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Container/Container.php(770): Illuminate\\Container\\Container->build()
#1 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(856): Illuminate\\Container\\Container->resolve()
#2 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Container/Container.php(706): Illuminate\\Foundation\\Application->resolve()
#3 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(841): Illuminate\\Container\\Container->make()
#4 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Routing/Route.php(274): Illuminate\\Foundation\\Application->make()
#5 /home/x/xx-deploy/xx/18122023_100452/vendor/formfeed-uk/nova-breadcrumbs/src/Http/Middleware/InterceptBreadcrumbs.php(29): Illuminate\\Routing\\Route->getController()
#6 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Formfeed\\Breadcrumbs\\Http\\Middleware\\InterceptBreadcrumbs->handle()
#7 /home/x/xx-deploy/xx/18122023_100452/app/Http/Middleware/EditorAdminDeveloperUserRole.php(23): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#8 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\EditorAdminDeveloperUserRole->handle()
#9 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/nova/src/Http/Middleware/BootTools.php(20): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#10 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Laravel\\Nova\\Http\\Middleware\\BootTools->handle()
#11 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/nova/src/Http/Middleware/DispatchServingNovaEvent.php(33): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#12 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Laravel\\Nova\\Http\\Middleware\\DispatchServingNovaEvent->handle()
#13 /home/x/xx-deploy/xx/18122023_100452/vendor/inertiajs/inertia-laravel/src/Middleware.php(87): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#14 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/nova/src/Http/Middleware/HandleInertiaRequests.php(70): Inertia\\Middleware->handle()
#15 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Laravel\\Nova\\Http\\Middleware\\HandleInertiaRequests->handle()
#16 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#17 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#18 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#19 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/nova/src/Http/Middleware/Authenticate.php(31): Illuminate\\Auth\\Middleware\\Authenticate->handle()
#20 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Laravel\\Nova\\Http\\Middleware\\Authenticate->handle()
#21 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#23 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#25 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#27 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle()
#28 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#30 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#32 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Routing/Router.php(799): Illuminate\\Pipeline\\Pipeline->then()
#34 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Routing/Router.php(776): Illuminate\\Routing\\Router->runRouteWithinStack()
#35 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Routing/Router.php(740): Illuminate\\Routing\\Router->runRoute()
#36 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Routing/Router.php(729): Illuminate\\Routing\\Router->dispatchToRoute()
#37 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(190): Illuminate\\Routing\\Router->dispatch()
#38 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#39 /home/x/xx-deploy/xx/18122023_100452/vendor/livewire/livewire/src/DisableBrowserCache.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#40 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Livewire\\DisableBrowserCache->handle()
#41 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/nova/src/Http/Middleware/ServeNova.php(23): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#42 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Laravel\\Nova\\Http\\Middleware\\ServeNova->handle()
#43 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#45 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#46 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#47 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#48 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#49 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#50 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#51 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#52 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#53 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#54 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\HandleCors->handle()
#55 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#56 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#57 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#58 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Pipeline\\Pipeline->then()
#59 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(134): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#60 /home/x/xx-deploy/xx/18122023_100452/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
#61 {main}

[previous exception] [object] (ReflectionException(code: -1): Class \"O:47:\"Laravel\\SerializableClosure\\SerializableClosure\":1:{s:12:\"serializable\";O:46:\"Laravel\\SerializableClosure\\Serializers\\Signed\":2:{s:12:\"serializable\";s:356:\"O:46:\"Laravel\\SerializableClosure\\Serializers\\Native\":5:{s:3:\"use\";a:1:{s:4:\"path\";s:13:\"nova-settings\";}s:8:\"function\";s:95:\"fn ($pageId = 'general') => inertia('NovaSettings', ['basePath' => $path, 'pageId' => $pageId])\";s:5:\"scope\";s:48:\"Outl1ne\\NovaSettings\\NovaSettingsServiceProvider\";s:4:\"this\";N;s:4:\"self\";s:32:\"00000000000008330000000000000000\";}\";s:4:\"hash\";s:44:\"f339LyrqsU40URDGjug6LvWDqCA29w5A/v5HpjWEpW8=\";}}\" does not exist at /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Container/Container.php:889)
[stacktrace]
#0 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Container/Container.php(889): ReflectionClass->__construct()
#1 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Container/Container.php(770): Illuminate\\Container\\Container->build()
#2 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(856): Illuminate\\Container\\Container->resolve()
#3 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Container/Container.php(706): Illuminate\\Foundation\\Application->resolve()
#4 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(841): Illuminate\\Container\\Container->make()
#5 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Routing/Route.php(274): Illuminate\\Foundation\\Application->make()
#6 /home/x/xx-deploy/xx/18122023_100452/vendor/formfeed-uk/nova-breadcrumbs/src/Http/Middleware/InterceptBreadcrumbs.php(29): Illuminate\\Routing\\Route->getController()
#7 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Formfeed\\Breadcrumbs\\Http\\Middleware\\InterceptBreadcrumbs->handle()
#8 /home/x/xx-deploy/xx/18122023_100452/app/Http/Middleware/EditorAdminDeveloperUserRole.php(23): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#9 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\EditorAdminDeveloperUserRole->handle()
#10 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/nova/src/Http/Middleware/BootTools.php(20): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#11 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Laravel\\Nova\\Http\\Middleware\\BootTools->handle()
#12 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/nova/src/Http/Middleware/DispatchServingNovaEvent.php(33): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#13 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Laravel\\Nova\\Http\\Middleware\\DispatchServingNovaEvent->handle()
#14 /home/x/xx-deploy/xx/18122023_100452/vendor/inertiajs/inertia-laravel/src/Middleware.php(87): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#15 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/nova/src/Http/Middleware/HandleInertiaRequests.php(70): Inertia\\Middleware->handle()
#16 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Laravel\\Nova\\Http\\Middleware\\HandleInertiaRequests->handle()
#17 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#19 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#20 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/nova/src/Http/Middleware/Authenticate.php(31): Illuminate\\Auth\\Middleware\\Authenticate->handle()
#21 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Laravel\\Nova\\Http\\Middleware\\Authenticate->handle()
#22 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#24 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#26 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#28 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle()
#29 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#30 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#31 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#33 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#34 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Routing/Router.php(799): Illuminate\\Pipeline\\Pipeline->then()
#35 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Routing/Router.php(776): Illuminate\\Routing\\Router->runRouteWithinStack()
#36 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Routing/Router.php(740): Illuminate\\Routing\\Router->runRoute()
#37 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Routing/Router.php(729): Illuminate\\Routing\\Router->dispatchToRoute()
#38 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(190): Illuminate\\Routing\\Router->dispatch()
#39 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#40 /home/x/xx-deploy/xx/18122023_100452/vendor/livewire/livewire/src/DisableBrowserCache.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Livewire\\DisableBrowserCache->handle()
#42 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/nova/src/Http/Middleware/ServeNova.php(23): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#43 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Laravel\\Nova\\Http\\Middleware\\ServeNova->handle()
#44 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#45 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#46 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#47 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#49 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#50 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#51 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#52 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#53 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#54 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#55 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\HandleCors->handle()
#56 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#57 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#58 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#59 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Pipeline\\Pipeline->then()
#60 /home/x/xx-deploy/xx/18122023_100452/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(134): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#61 /home/x/xx-deploy/xx/18122023_100452/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
#62 {main}
"} 



```

**Comment by aliwesome** [comment]
@flatcapco I faced this issue right now on Nova v4, did you find a fix?

**Comment by flatcapco** [comment]
> @flatcapco I faced this issue right now on Nova v4, did you find a fix?

nope sorry
